yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path("create/", views.post_create, name="post_create"),
]

yatube/users/urls.py
# Импортируем из приложения django.contrib.auth нужный view-класс
from django.contrib.auth.views import LoginView, LogoutView, \
    PasswordResetView, PasswordChangeView, PasswordChangeDoneView, \
    PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('password_reset/',
         PasswordResetView.as_view(
             template_name='users/password_reset_form.html'),
         name='password_reset_form'
         ),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'
         ),
    path('password_change/',
         PasswordChangeView.as_view(
             template_name='users/password_change_form.html'),
         name='password_change_form'
         ),
    path('password_change/done/',
         PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'),
         name='password_change_done'
         ),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'
         ),
    path('reset/done/',
         PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'
         ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='auth')),
    path('auth/', include('django.contrib.auth.urls')),

]

yatube/templates/includes/block.html
<article>
    <ul>
        <li>
            Автор: {{ post.author.get_full_name }}
        </li>
        <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
    </ul>
    <p>
        {{ post.text|linebreaksbr }}
    </p>
    {% if not group and post.group.id > 0 %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи
        группы {{ post.group }}</a>
    {% endif %}
</article>

yatube/templates/includes/footer.html
      <p>© {{ year }} Copyright <span style="color:red">Yo</span>tube</p>

yatube/templates/includes/form.html
{% load user_filters %}
                {% if form.errors %}
                    {% for field in form %}
                      {% for error in field.errors %}
                        <div class="alert alert-danger">
                          {{ error|escape }}
                        </div>
                      {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                {% endif %}

                <form method="post"
                >
                {% csrf_token %}

                {% for field in form %}
                  <div class="form-group row my-3 p-3"
                    {% if field.field.required %}
                      aria-required="true"
                    {% else %}
                      aria-required="false"
                    {% endif %}
                  >
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                        {% if field.field.required %}
                          <span class="required text-danger">*</span>
                        {% endif %}
                    </label>
                    <div>
                    {{ field|addclass:'form-control' }}
                      {% if field.help_text %}
                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                          {{ field.help_text|safe }}
                        </small>
                      {% endif %}
                    </div>
                  </div>
                {% endfor %}
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      {% if action == 'edit' %}
                        Сохранить
                      {% elif action == 'create' %}
                        Добавить
                      {% else %}
                        Подтвердить
                      {% endif %}
                    </button>

                  </div>
                </form>

yatube/templates/includes/head.html
{% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180"
          href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32"
          href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16"
          href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

yatube/templates/includes/header.html
{% load static %}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Yo</span>tube
      </a>

      {% with request.resolver_match.view_name as view_name %}

      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
             href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
             href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated  %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'auth:password_change_form' %}active{% endif %}"
             href="{% url 'auth:password_change_form' %}">Изменить пароль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light " href="{% url 'auth:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'auth:login' %}active{% endif %}"
             href="{% url 'auth:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'auth:signup' %}active{% endif %}"
             href="{% url 'auth:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
      {% endwith %}

    </div>
  </nav>